version: "3.3"
services:
  audio-server:
    container_name: audio-server
    environment:
      - NODE_ENV=develop
    restart: "unless-stopped"
    build: .
    command: yarn run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
